## YAML Template.
---    
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        - id: customer_service
          uri: lb://businessdomain-customer
          predicates:
              ##Este se coloca para que lea el swagger, si no, es customer
              ##- Path=/customer/**
            - Path=/**